### ISSUE TITLE
copyartifacts ignoring files

### ISSUE THREAD

**Issue by devster31** [sbarakat/beets-copyartifacts#37]
I'm trying to import a FLAC album, below my configuration:
```yaml
paths:
    ext:log: $albumpath/$album%if{$multidisc, - Disc $disc}
    ext:cue: $albumpath/$album%if{$multidisc, - Disc $disc}
    ext:jpg: $albumpath/original_cover

item_fields:
    multidisc: 1 if disctotal > 1 else 0

copyartifacts:
    extensions: .cue .log .jpg
    print_ignored: yes
```
And here the output of an example import:
```sh
$ beet import Yeezus\ -\ Kanye\ West\ \[2013\]\ \(FLAC\)/

/downloads/music/mutracker/Yeezus - Kanye West [2013] (FLAC) (10 items)
Tagging:
    Kanye West - Yeezus
URL:
    https://musicbrainz.org/release/d607b7f8-9d2f-4387-be7c-0693d185d272
(Similarity: 100.0%) (CD, 2013, GB, Def Jam Recordings)
 * I Am A God (feat. God) -> I Am a God (feat. God)
 * I'm In It              -> I'm in It
 * Blood On The Leaves    -> Blood on the Leaves
copyartifacts: Ignored files:
copyartifacts:    02 - Black Skinhead.flac
copyartifacts:    03 - I Am A God (feat. God).flac
copyartifacts:    04 - New Slaves.flac
copyartifacts:    05 - Hold My Liquor.flac
copyartifacts:    06 - I'm In It.flac
copyartifacts:    07 - Blood On The Leaves.flac
copyartifacts:    08 - Guilt Trip.flac
copyartifacts:    09 - Send It Up.flac
copyartifacts:    10 - Bound 2.flac
copyartifacts:    Kanye West - Yeezus [2013].cue
copyartifacts:    Kanye West - Yeezus.jpg
copyartifacts:    Kanye West - Yeezus.log
copyartifacts:    Kanye West - Yeezus.m3u
```
What am I missing?
