### ISSUE TITLE
Plugin forgets settings when resuming an import

### ISSUE THREAD

**Issue by 8h2a** [sbarakat/beets-copyartifacts#41]
I have the following config (snippet):
```yaml
import:
    move: no
    copy: yes
    write: yes

copyartifacts:
    extensions: .*
    print_ignored: yes
```

Which should only copy files, which works perfectly fine,
unless I resume a previously interrupted import.
When I do that, it moves the files instead of copying them.
